### ISSUE TITLE
USE JACK

### ISSUE THREAD

**Issue by jrddunbr** [Grissess/my3status#1]
You know that these kinds of things are easier to find in `/sys/class/net`, right?

https://github.com/Grissess/my3status/blob/master/status.py#L110-L149

**Comment by Grissess** [comment]
First off, that's not necessarily portable; sysfs is a Linux thing. I'll admit this is mostly for my consumption, though, so that's not as material as the next point.

Second: while it can be used to list interfaces and detect carrier, the _address and mask_ need to be gotten either through a clunky single-family BSD interface, or through an `ioctl` (specifically `SIOCGIF{ADDR,NETMASK}`) whose value is not exposed in Python (likely due to dependence, e.g., on kernel headers, that bindist Python can't account for). Python does expose `ioctl`, but getting those constants is a pain; [netifaces](https://github.com/al45tair/netifaces) does this well enough.

Third, a minor nitpick: I know it took a while for me to find this issue, but--if you're linking against a specific version of a file--do link against the blob, not through the branch ref. Tap `y` on GitHub to resolve the ref to the blob in your address bar :)

**Comment by jrddunbr** [comment]
> First off, that's not necessarily portable; sysfs is a Linux thing. I'll admit this is mostly for my consumption, though, so that's not as material as the next point.

Dare you to run i3 on non-Linux :P

**Comment by Grissess** [comment]
> Dare you to run i3 on non-Linux :P

That's exactly what I'm admitting :P
